### ISSUE TITLE
Adding 'attribute' on the 'configure_user' for other database systems.

### ISSUE THREAD

**Issue by songmink** [mingchen/django-cas-ng#141]
My company uses a CAS based on LDAP system. It uses different attributes names. For example, my company server returns 'givenName' as 'first_name', 'sn' for 'last_name' etc. If the 'configure_user()' can get the attributes, it is easy to add user information on other models.
`
configure_user(self, user, attributes)
`

**Comment by danizen** [comment]
@songmink, I think you can implement this today using the cas_user_authenticated signal.   See my issue #115 - I originally thought I needed to change the base, but I merely needed to subscribe to the signal and log.  I think you are in a similar situation because both the user and the attributes are included in the signal.

**Comment by mingchen** [comment]
Closed due in-active.
