### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by zhangfy** [mingchen/django-cas-ng#168]
I use django-cas-ng to access sso.But I find some users have the problem "too many redirects".
I can get ticket from sso and create session in session store, can't find cookie in the browser.I think this is the problem why "too many redirects". I find the code "request.session.create()" in django-cas-ng, but I think it dosen't work!

**Comment by duoi** [comment]
Seems to work for me. Are you sure your users have cookies enabled?

Can you post a trace with the redirects you're experiencing? It shouldn't be that many.

**Comment by PhilippeTrounev** [comment]
Just an update from us. We are also using this, I find this issue is mostly unique to the safari browser, i've tried to mediate it the best I can, but it keeps throwing too many redirects on sign-in/sign-up when I use the safari browser. Safari does not like that when I try to login through CAS, CAS redirects it back to /login/?service... which redirects to our app on successful authentication. Which leads to too many redirects.

**Comment by duoi** [comment]
@PhilippeTrounev can you share your monkey patch? We might be able to merge it upstream.
