### ISSUE TITLE
Update example in README to use the class-based views

### ISSUE THREAD

**Issue by piotrb5e3** [mingchen/django-cas-ng#190]
Because of #179 the examples won't work, and could cause more issues like #189 .

**Comment by mingchen** [comment]
PR welcome.

**Comment by jordiecometrica** [comment]
This still isn't fixed:

https://github.com/mingchen/django-cas-ng#view-wrappers-example

I'm trying to figure out how to fix this, but I'm not sure how to actually log in anymore.

The `post` method of `LoginView` has a bug, because it return `None` unless that parameter is defined:

https://github.com/mingchen/django-cas-ng/blob/master/django_cas_ng/views.py#L52

I'll think about this a bit more and see if I can figure out how to do this.
