### ISSUE TITLE
Single Sign Out

### ISSUE THREAD

**Issue by manelclos** [mingchen/django-cas-ng#82]
Hi,

I'm using django_cas_ng as a client to django-mama-cas (https://github.com/jbittel/django-mama-cas), so far so good both work perfect together.

Tried to use single sign out today, and got some problems:

First, django-mama-cas does not send the "logoutRequest" that some servers send, but only the xml payload in the post request body, so I changed the code in views.py:46 like this:

    if request.method == 'POST' and (request.POST.get('logoutRequest') or request.META.get('CONTENT_TYPE') == 'text/xml'):

and also in views:154 like this:

def clean_sessions(client, request):
    for slo in client.get_saml_slos(request.body):

I could not find any resource telling the standard requires the server to set logoutRequest.

Second, you need to be running version 3:
CAS_VERSION = 3

otherwise you get: 'CASClientV2' object has no attribute 'get_saml_slos'

After these changes everything works as expected!

Can these changes be incorporated into django_cas_ng? should I create a proper PR supporting both use cases (with and without logoutRequest parameter)?

Thanks in advance!

**Comment by nitmir** [comment]
The jasig CAS (the mainline implementation) send the logout request in a POST parameter called logoutRequest.
You can also see that phpCAS use this POST parameter to see if the request is a logout request https://github.com/Jasig/phpCAS/blob/master/source/CAS/Client.php#L1696.
Idem for rubycas-client-rails https://github.com/rubycas/rubycas-client-rails/blob/master/lib/rubycas-client-rails.rb#L290 or the omniauth-cas client https://docs.omniref.com/ruby/gems/eriko-omniauth-cas/1.0.5/symbols/OmniAuth::Strategies::CAS::LogoutRequest#line=34

I think it could be easier to have mama-cas to send the POST parameter than to modify all CAS clients.

We should not be checking for logout request if CAS_VERSION < 3 as it is only suported by CAS_VERSION == 3 and SAML 1.1.

I personally do not use django-mama-cas because I found its policy about who can get a ProxyGrantingTicket way too permissive. The mainline jasig CAS server require [each registered application in the registry to be explicitly configured to allow for proxy authentication](http://jasig.github.io/cas/development/installation/Configuring-Proxy-Authentication.html).
For your information (I do not know if you are familiar with the CAS protocol) once something get a ProxyGrantingTicket for a user, it can connect pretty much to every apps using the CAS as this user. At the current time, every services allowed to authenticate against the CAS (ie inside MAMA_CAS_VALID_SERVICES) are de-facto allowed to retrieve a PGT https://github.com/jbittel/django-mama-cas/issues/26

**Comment by manelclos** [comment]
Hi,

Yes, I see your point. Let me ask django-mama-cas project about that.

Thanks for the prompt reply!

**Comment by jbittel** [comment]
I am planning to rework how services are validated in django-mama-cas to allow for per-service configuration, including allowing/disallowing proxy authentication. Thanks for the reminder!

**Comment by manelclos** [comment]
Hi, this has been fixed in django-mama-cas, thank you!

https://github.com/jbittel/django-mama-cas/issues/27
